version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y awscli
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH      
      - aws s3 cp s3://$BUCKET/kubeconfig /root/.kube/config

      
  pre_build:
    commands:
      -  aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY_URL
      -  aws s3 cp s3://$BUCKET/.env .
      -  docker build -t web:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      -  docker tag web:$CODEBUILD_RESOLVED_SOURCE_VERSION $DOCKER_REGISTRY_URL:web-$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - docker push $DOCKER_REGISTRY_URL:web-$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - sed "s|DOCKER_REGISTRY_URL|$DOCKER_REGISTRY_URL|g" deployment.yml > deployment_temp.yml
      - sed "s|VERSION|$CODEBUILD_RESOLVED_SOURCE_VERSION|g" deployment_temp.yml > deployment_temp_result.yml
      - mv deployment_temp_result.yml deployment.yml
      - kubectl apply -f deployment.yml
