apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers: #
      - name: web
        image: DOCKER_REGISTRY_URL:web-VERSION
        ports:
        - containerPort: 4000


---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: web
    name: web-svc
spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 4000
    selector:
        app: web
    type: ClusterIP
